Lama_Store/Models/LlOrder.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Lama_Store.Models
{
    public partial class LlOrder
    {
        public LlOrder()
        {
            LlProductOrders = new HashSet<LlProductOrder>();
        }

        public decimal OrderId { get; set; }
        public string OrderName { get; set; }
        public decimal? UserId { get; set; }
        public decimal? VisaId { get; set; }

        public virtual LlUser User { get; set; }
        public virtual LlVisa Visa { get; set; }
        public virtual ICollection<LlProductOrder> LlProductOrders { get; set; }
    }
}

Lama_Store/Controllers/LlOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lama_Store.Models;
using Microsoft.AspNetCore.Http;
using System.Net.Mail;
using System.Net;
using EASendMail;

namespace Lama_Store.Controllers
{
    public class LlOrdersController : Controller
    {
        private readonly ModelContext _context;

        public LlOrdersController(ModelContext context)
        {
            _context = context;
        }

        // GET: LlOrders
        public async Task<IActionResult> Index()
        {
            var modelContext = _context.LlOrders.Include(l => l.User).Include(l => l.Visa);
            return View(await modelContext.ToListAsync());
        }

        // GET: LlOrders/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llOrder = await _context.LlOrders
                .Include(l => l.User)
                .Include(l => l.Visa)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (llOrder == null)
            {
                return NotFound();
            }

            return View(llOrder);
        }
        public async Task<IActionResult> AddToCart(int id)
        {
            LlProduct resultItem = _context.LlProducts.Where(x => x.ProductId == id).SingleOrDefault();
            LlOrder order = new LlOrder();
            order.OrderName = resultItem.ProductName;
            order.UserId = HttpContext.Session.GetInt32("UserId");
            _context.Add(order);
            await _context.SaveChangesAsync();

            return RedirectToAction("Sales","LlProducts");
        }

        public IActionResult ViewCart() {
            int? currentUser = HttpContext.Session.GetInt32("UserId");

            var result = _context.LlOrders.Where(x => x.UserId == currentUser);
            var result2 = _context.LlProducts.Where(x => x.ProductId > 0);
            var eventsQry = from Or in result
                            join Pr in result2 on Or.OrderName equals Pr.ProductName
                            where Or.OrderName == Pr.ProductName select new NewClass(Or.OrderName, 
                            Pr.ImagePathP,
                            Pr.ProductCost,
                            Pr.ProductPrice,
                            Pr.ProductId
                            );
            return View(eventsQry.ToList());
        }
        public IActionResult Checkout()
        {
            int? currentUser = HttpContext.Session.GetInt32("UserId");

            var result = _context.LlOrders.Where(x => x.UserId == currentUser);
            var result2 = _context.LlProducts.Where(x => x.ProductId > 0);
            var eventsQry = from Or in result
                            join Pr in result2 on Or.OrderName equals Pr.ProductName
                            where Or.OrderName == Pr.ProductName
                            select new NewClass(Or.OrderName,
                            Pr.ImagePathP,
                            Pr.ProductCost,
                            Pr.ProductPrice,
                            Pr.ProductId
            );
            return View(eventsQry.ToList());
        }


        [HttpPost]
        public IActionResult SendEmail(string add1,string city,string zip, string Email)
        {
            int? currentUser = HttpContext.Session.GetInt32("UserId");

            var result = _context.LlOrders.Where(x => x.UserId == currentUser).ToList();
            string items = "";
            for (int i = 0; i < result.Count(); i++) {
                items += " 1x "+ result.ElementAt(i) + "\r\n ";
            }
            string message = "Thank you for your purchase from EStore \r\n" +
                "Your order is as follows:\r\n" + items +
                " Which will be Delived to \r\n add1";

            try
            {
                if (ModelState.IsValid)
                {
                    SmtpMail oMail = new SmtpMail("TryIt");

                    // Your email address
                    oMail.From = "khaledxz150@hotmail.com";

                    // Set recipient email address
                    oMail.To = Email;

                    // Set email subject
                    oMail.Subject = "Purchase from EStore";

                    // Set email body
                    oMail.TextBody = message;

                    // Hotmail/Outlook SMTP server address
                    SmtpServer oServer = new SmtpServer("smtp.office365.com");

                    // If your account is office 365, please change to Office 365 SMTP server
                    // SmtpServer oServer = new SmtpServer("smtp.office365.com");

                    // User authentication should use your
                    // email address as the user name.
                    oServer.User = "khaledxz150@hotmail.com";

                    // If you got authentication error, try to create an app password instead of your user password.
                    // https://support.microsoft.com/en-us/account-billing/using-app-passwords-with-apps-that-don-t-support-two-step-verification-5896ed9b-4263-e681-128a-a6f2979a7944
                    oServer.Password = "";

                    // use 587 TLS port
                    oServer.Port = 587;

                    // detect SSL/TLS connection automatically
                    oServer.ConnectType = SmtpConnectType.ConnectSSLAuto;


                    EASendMail.SmtpClient oSmtp = new EASendMail.SmtpClient();
                    oSmtp.SendMail(oServer, oMail);
                    return RedirectToAction("index","Home");
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Some Error";
            }
            return View();
        }




        // GET: LlOrders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.LlUsers, "UserId", "UserId");
            ViewData["VisaId"] = new SelectList(_context.LlVisas, "VisaId", "VisaId");
            return View();
        }

        // POST: LlOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,OrderName,UserId,VisaId")] LlOrder llOrder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(llOrder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.LlUsers, "UserId", "UserId", llOrder.UserId);
            ViewData["VisaId"] = new SelectList(_context.LlVisas, "VisaId", "VisaId", llOrder.VisaId);
            return View(llOrder);
        }

        // GET: LlOrders/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llOrder = await _context.LlOrders.FindAsync(id);
            if (llOrder == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.LlUsers, "UserId", "UserId", llOrder.UserId);
            ViewData["VisaId"] = new SelectList(_context.LlVisas, "VisaId", "VisaId", llOrder.VisaId);
            return View(llOrder);
        }

        // POST: LlOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("OrderId,OrderName,UserId,VisaId")] LlOrder llOrder)
        {
            if (id != llOrder.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(llOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LlOrderExists(llOrder.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.LlUsers, "UserId", "UserId", llOrder.UserId);
            ViewData["VisaId"] = new SelectList(_context.LlVisas, "VisaId", "VisaId", llOrder.VisaId);
            return View(llOrder);
        }

        // GET: LlOrders/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llOrder = await _context.LlOrders
                .Include(l => l.User)
                .Include(l => l.Visa)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (llOrder == null)
            {
                return NotFound();
            }

            return View(llOrder);
        }

        // POST: LlOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var llOrder = await _context.LlOrders.FindAsync(id);
            _context.LlOrders.Remove(llOrder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

Lama_Store/Views/LlOrders/CheckOut.cshtml
@using Lama_Store.Controllers
@model IEnumerable<NewClass>
@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
    decimal? Total = 5;
}


<section class="checkout_area section_padding">
    <div class="container">
      <div class="returning_customer">
     
        
      </div>
      
      <div class="billing_details">
        <div class="row">
          <div class="col-lg-8">
            <h3>Billing Details</h3>
            <form asp-action="SendEmail" asp-controller="LlOrders" class="row contact_form" method="post">
              <div class="col-md-6 form-group p_star">
                <input type="text" class="form-control" id="Email" name="Email" />
                <span class="placeholder" data-placeholder="Email Address"></span>
              </div>
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="add1" name="add1" />
                <span class="placeholder" data-placeholder="Address line 01"></span>
              </div>
              <div class="col-md-12 form-group p_star">
                <input type="text" class="form-control" id="city" name="city" />
                <span class="placeholder" data-placeholder="Town/City"></span>
              </div>
              <div class="col-md-12 form-group">
                <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP" />
              </div>
               <input type="submit" id="submit-form" class="hidden" hidden />
            </form>
          </div>
          <div class="col-lg-4">
            <div class="order_box">
              <h2>Your Order</h2>
              <ul class="list">
                <li>
                  <a>Product
                    <span>Total</span>
                  </a>
                </li>
                @foreach(var item in Model){
                   Total += @item.ProductPrice;
                   <li>
                  <a asp-action="SinglePage" asp-controller="LiProducts" asp-route-id="@item.ProductId">@item.ProductName
                    <span class="middle">x01</span>
                    <span class="last">@item.ProductPrice</span>
                    
                  </a>
                </li>}
              </ul>
              <ul class="list list_2">
                <li>
                  <a>Subtotal
                    <span>$@Total
                    </span>
                  </a>
              </ul>
              <div class="payment_item">
                <div class="radion_btn">
                  <input type="radio" id="f-option5" name="selector" />
                  <label for="f-option5">Check payments</label>
                  <div class="check"></div>
                </div>
                <p>
                  Send Email with information of Order
                </p>
              </div>
              <div class="payment_item active">
                <div class="radion_btn">
                  <input type="radio" id="f-option6" name="selector" />
                  <label for="f-option6">Paypal </label>
                  <img src="img/product/single-product/card.jpg" alt="" />
                  <div class="check"></div>
                </div>
                <p>
                  Please send a check to Store Name, Store Street, Store Town,
                  Store State / County, Store Postcode.
                </p>
              </div>
              <div class="creat_account">
                <input type="checkbox" id="f-option4" name="selector" />
                <label for="f-option4">I’ve read and accept the </label>
                <a href="#">terms & conditions*</a>
              </div>
               <label for="submit-form" tabindex="0" class="button123 btn_3">Submit</label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

Lama_Store/Views/LlOrders/Create.cshtml
@model Lama_Store.Models.LlOrder

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LlOrder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderName" class="control-label"></label>
                <input asp-for="OrderName" class="form-control" />
                <span asp-validation-for="OrderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="VisaId" class="control-label"></label>
                <select asp-for="VisaId" class ="form-control" asp-items="ViewBag.VisaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lama_Store/Views/LlOrders/Delete.cshtml
@model Lama_Store.Models.LlOrder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LlOrder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Visa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Visa.VisaId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lama_Store/Views/LlOrders/Details.cshtml
@model Lama_Store.Models.LlOrder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LlOrder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Visa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Visa.VisaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lama_Store/Views/LlOrders/Edit.cshtml
@model Lama_Store.Models.LlOrder

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LlOrder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="OrderName" class="control-label"></label>
                <input asp-for="OrderName" class="form-control" />
                <span asp-validation-for="OrderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VisaId" class="control-label"></label>
                <select asp-for="VisaId" class="form-control" asp-items="ViewBag.VisaId"></select>
                <span asp-validation-for="VisaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lama_Store/Views/LlOrders/Index.cshtml
@model IEnumerable<Lama_Store.Models.LlOrder>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Visa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Visa.VisaId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Lama_Store/Views/LlOrders/ViewCart.cshtml
@using Lama_Store.Controllers
@model IEnumerable<NewClass>
@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
    decimal? Total = 5;
}

<section class="cart_area section_padding">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
                @foreach(var item in Model){
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                     <img src=@Url.Content("~/Image/" + item.Image) asp-append-version="true" 
                     style="border-radius:20%; height:250px;width:250px" />
                    </div>
                    <div class="media-body">
                      <h3>@item.ProductName</h3>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>@item.ProductPrice</h5>
                </td>
                <td>
                  <div class="product_count">
                    <span class="input-number-decrement"> <i class="ti-minus"></i></span>
                    <input class="input-number" type="text" value="1" min="0" max="10">
                    <span class="input-number-increment"> <i class="ti-plus"></i></span>
                  </div>
                </td>
                <td>
                  <h4>@item.ProductPrice</h4>
                </td>
              </tr>
               Total+=item.ProductPrice;
              }
              <tr class="bottom_button">
                <td>
                  <a class="btn_1" asp-action="ViewCart" asp-controller="LlOrders">Update Cart</a>
                </td>
                <td></td>
                <td></td>
                <td>
                
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h4>Subtotal</h4>
                </td>
                <td>
                  <h4>@Total</h4>
                </td>
              </tr>
              <tr class="shipping_area">
                <td></td>
                <td></td>
                <td>
                  <h5>Shipping</h5>
                </td>
                <td>
                  <div class="shipping_box">
                    <ul class="list">
                      <li>
                        Flat Rate: $5.00
                      </li>
                    
                    </ul>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="#">Continue Shopping</a>
            <a class="btn_1 checkout_btn_1" asp-controller="LlOrders" asp-action="Checkout">Proceed to checkout</a>
          </div>
        </div>
      </div>
      </div>
  </section>