Lama_Store/Models/LlProduct.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Lama_Store.Models
{
    public partial class LlProduct
    {
       

        public decimal ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal? ProductPrice { get; set; }
        public string ImagePathP { get; set; }
        public decimal? ProductCost { get; set; }
        public decimal? StoreId { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }


        public virtual LlStore Store { get; set; }
        public virtual ICollection<LlProductOrder> LlProductOrders { get; set; }
    }
}

Lama_Store/Controllers/LlProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lama_Store.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Lama_Store.Controllers
{
    public class LlProductsController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;

        public LlProductsController(ModelContext context, IWebHostEnvironment webHostEnviroment)
        {
            _context = context;
            _webHostEnviroment = webHostEnviroment;

        }

        // GET: LlProducts
        public async Task<IActionResult> Index()
        {
            var modelContext = _context.LlProducts.Include(l => l.Store);
            return View(await modelContext.ToListAsync());
        }

        public  IActionResult SinglePage(int id)
        {
            int? user = HttpContext.Session.GetInt32("UserId");
            if (user == null)
            {
                int? CartCount = _context.LlOrders.Where(x => x.UserId == user).Count();
                if (CartCount == 0 || CartCount == null)
                    ViewBag.CartCount = 0;
                else
                {
                    ViewBag.CartCount = CartCount;
                }
            }
            var modelContext = _context.LlProducts.Where(l => l.ProductId == id).ToList();
            return View(modelContext);
        }

        public async Task<IActionResult> Sales(decimal? id)
        {
            int? user = HttpContext.Session.GetInt32("UserId");
            if (user == null)
            {
                int? CartCount = _context.LlOrders.Where(x => x.UserId == user).Count();
                if (CartCount == 0 || CartCount == null)
                    ViewBag.CartCount = 0;
                else
                {
                    ViewBag.CartCount = CartCount;
                }
            }
            if (id != null) {
                var result = _context.LlProducts.Where(x=>x.StoreId == (int)id).Include(i => i.Store);
                return View(await result.ToListAsync());
            }
            var modelContext = _context.LlProducts.Include(l => l.Store);
            return View(await modelContext.ToListAsync());
        }
        // GET: LlProducts/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llProduct = await _context.LlProducts
                .Include(l => l.Store)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (llProduct == null)
            {
                return NotFound();
            }

            return View(llProduct);
        }

        // GET: LlProducts/Create
        public IActionResult Create()
        {
            ViewData["StoreId"] = new SelectList(_context.LlStores, "StoreId", "StoreName");
            return View();
        }

        // POST: LlProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,ImagePathP,ProductCost,StoreId,ImageFile")] LlProduct llProduct)
        {
            if (ModelState.IsValid)
            {
                if (llProduct.ImageFile != null)
                {
                    //1- get w3rootpath
                    string w3rootpath = _webHostEnviroment.WebRootPath;
                    //Guid.newguid : generate unique string before image name ;
                    ////2- generate image name and add unique string
                    string fileName = Guid.NewGuid().ToString() + "_" + llProduct.ImageFile.FileName; //ex : affscdw5635edvcywydfew_Aseel.jpg
                                                                                                       //3- path
                    string path = Path.Combine(w3rootpath + "/Image/" + fileName);
                    //4-create Image inside image file in w3root folder
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await llProduct.ImageFile.CopyToAsync(fileStream);
                    }


                    llProduct.ImagePathP = fileName; //ex : affscdw5635edvcywydfew_Aseel.jpg stor in DB
                }
                _context.Add(llProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.LlStores, "StoreId", "StoreName", llProduct.StoreId);
            return View(llProduct);
        }

        // GET: LlProducts/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llProduct = await _context.LlProducts.FindAsync(id);
            if (llProduct == null)
            {
                return NotFound();
            }
            ViewData["StoreId"] = new SelectList(_context.LlStores, "StoreId", "StoreId", llProduct.StoreId);
            return View(llProduct);
        }

        // POST: LlProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("ProductId,ProductName,ProductPrice,ImagePathP,ProductCost,StoreId,ImageFile")] LlProduct llProduct)
        {
            if (id != llProduct.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (llProduct.ImageFile != null)
                    {
                        //1- get w3rootpath
                        string w3rootpath = _webHostEnviroment.WebRootPath;
                        //Guid.newguid : generate unique string before image name ;
                        ////2- generate image name and add unique string
                        string fileName = Guid.NewGuid().ToString() + "_" + llProduct.ImageFile.FileName; //ex : affscdw5635edvcywydfew_Aseel.jpg
                                                                                                          //3- path
                        string path = Path.Combine(w3rootpath + "/Image/" + fileName);
                        //4-create Image inside image file in w3root folder
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await llProduct.ImageFile.CopyToAsync(fileStream);
                        }


                        llProduct.ImagePathP = fileName; //ex : affscdw5635edvcywydfew_Aseel.jpg stor in DB
                    }
                    _context.Update(llProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LlProductExists(llProduct.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.LlStores, "StoreId", "StoreId", llProduct.StoreId);
            return View(llProduct);
        }

        // GET: LlProducts/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var llProduct = await _context.LlProducts
                .Include(l => l.Store)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (llProduct == null)
            {
                return NotFound();
            }

            return View(llProduct);
        }

        // POST: LlProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var llProduct = await _context.LlProducts.FindAsync(id);
            _context.LlProducts.Remove(llProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LlProductExists(decimal id)
        {
            return _context.LlProducts.Any(e => e.ProductId == id);
        }
    }
}

Lama_Store/Views/LlProducts/Create.cshtml
@model Lama_Store.Models.LlProduct

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LlProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCost" class="control-label"></label>
                <input asp-for="ProductCost" class="form-control" />
                <span asp-validation-for="ProductCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class ="form-control" asp-items="ViewBag.StoreId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lama_Store/Views/LlProducts/Delete.cshtml
@model Lama_Store.Models.LlProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LlProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePathP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePathP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lama_Store/Views/LlProducts/Details.cshtml
@model Lama_Store.Models.LlProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LlProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePathP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePathP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lama_Store/Views/LlProducts/Edit.cshtml
@model Lama_Store.Models.LlProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>LlProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCost" class="control-label"></label>
                <input asp-for="ProductCost" class="form-control" />
                <span asp-validation-for="ProductCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class="form-control" asp-items="ViewBag.StoreId"></select>
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lama_Store/Views/LlProducts/Index.cshtml
@model IEnumerable<Lama_Store.Models.LlProduct>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePathP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                <img src=@Url.Content("~/Image/" + item.ImagePathP)
                     asp-append-version="true" style="border-radius:20%;" width="100" height="100" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store.StoreName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Lama_Store/Views/LlProducts/Sales.cshtml
  @model IEnumerable<Lama_Store.Models.LlProduct>

      
@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";


}
<main>

        <!-- slider Area Start-->
        <div class="slider-area ">
            <!-- Mobile Menu -->
            <div class="single-slider slider-height2 d-flex align-items-center" background="~/assets/img/hero/category.jpg">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Product Catagori</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- slider Area End-->

        <!-- Latest Products Start -->
        <section class="latest-product-area latest-padding">
            <div class="container">
                <div class="row product-btn d-flex justify-content-between">
                        <div class="properties__button">
                            <!--Nav Button  -->
                            <nav>                                                                                                
                                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            @{
                                var unique = Model.Select(i=>new {i.Store, i.StoreId }).Distinct();
                                foreach(var item in unique)
                                {
                               <a class="nav-item nav-link" id="nav-home-tab"  asp-controller="LlProducts" asp-action="Sales" asp-route-id="@item.StoreId" role="tab" aria-controls="nav-home" >@item.Store.StoreName</a>
                                }
                            }
                                </div>
                            </nav>
                            <!--End Nav Button  -->
                        </div>
                </div>
                <!-- Nav Card -->
                <div class="tab-content" id="nav-tabContent">
                    <!-- card one -->

                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <div class="row">
                             @foreach (var item in Model)
                {
                      <div class="col-xl-4 col-lg-4 col-md-6">
                                <div class="single-product mb-60">
                                    <div class="product-img">
                                                    <img src=@Url.Content("~/Image/" + item.ImagePathP) asp-append-version="true" style="border-radius:20%; height:300px;width:300px" />
                                        <div class="new-product">
                                        </div>
                                    </div>
                                    <div class="product-caption">
                                         <div class="product-ratting">
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star low-star"></i>
                                        <i class="far fa-star low-star"></i>
                                    </div>
                                        <h4><a asp-action="SinglePage" asp-controller="LlProducts" asp-route-id="@item.ProductId">@item.ProductName</a></h4>
                                        <div class="price">
                                            <ul>
                                                <li>$@item.ProductPrice</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                }
                            </div>
                         
                            </div>
                        </div>
                    </div>
                    <!-- Card two -->
                    
                <!-- End Nav Card -->
        </section>
        <!-- Latest Products End -->

        <!-- Latest Offers Start -->
        <div class="latest-wrapper lf-padding">
            <div class="latest-area latest-height d-flex align-items-center" data-background="~/assets/img/collection/latest-offer.png">
                <div class="container">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-5 col-lg-5 col-md-6 offset-xl-1 offset-lg-1">
                            <div class="latest-caption">
                                <h2>Get Our<br>Latest Offers News</h2>
                                <p>Subscribe news latter</p>
                            </div>
                        </div>
                            <div class="col-xl-5 col-lg-5 col-md-6 ">
                            <div class="latest-subscribe">
                                <form action="#">
                                    <input type="email" placeholder="Your email here">
                                    <button>Shop Now</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- man Shape -->
                <div class="man-shape">
                    <img src="~/assets/img/collection/latest-man.png" alt="">
                </div>
            </div>
        </div>
        <!-- Latest Offers End -->
        <!-- Shop Method Start-->
        <div class="shop-method-area section-padding30">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-6">
                        <div class="single-method mb-40">
                            <i class="ti-package"></i>
                            <h6>Free Shipping Method</h6>
                            <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6">
                        <div class="single-method mb-40">
                            <i class="ti-unlock"></i>
                            <h6>Secure Payment System</h6>
                            <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                        </div>
                    </div> 
                    <div class="col-xl-3 col-lg-3 col-md-6">
                        <div class="single-method mb-40">
                            <i class="ti-reload"></i>
                            <h6>Secure Payment System</h6>
                            <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Shop Method End-->
        <!-- Gallery Start-->
        <div class="gallery-wrapper lf-padding">
            <div class="gallery-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="gallery-items">
                            <img src="~/assets/img/gallery/gallery1.jpg" alt="">
                        </div> 
                        <div class="gallery-items">
                            <img src="~/assets/img/gallery/gallery2.jpg" alt="">
                        </div>
                        <div class="gallery-items">
                            <img src="~/assets/img/gallery/gallery3.jpg" alt="">
                        </div>
                        <div class="gallery-items">
                            <img src="~/assets/img/gallery/gallery4.jpg" alt="">
                        </div>
                        <div class="gallery-items">
                            <img src="~/assets/img/gallery/gallery5.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Gallery End-->

    </main>

Lama_Store/Views/LlProducts/SinglePage.cshtml
  @model IEnumerable<Lama_Store.Models.LlProduct>

@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@foreach(var item in Model){
<div class="product_image_area">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="product_img_slide owl-carousel">
            <div class="single_product_img">
             <img src=@Url.Content("~/Image/" + @item.ImagePathP) asp-append-version="true" alt="#" class="img-fluid">
            </div>
           
          </div>
        </div>
        <div class="col-lg-8">
          <div class="single_product_text text-center">
            <h3> @item.ProductName</h3>
           
            <div class="card_area">
                <div class="product_count_area">
                    <p>Quantity</p>
                    <div class="product_count d-inline-block">
                        <span class="product_count_item inumber-decrement"> <i class="ti-minus"></i></span>
                        <input class="product_count_item input-number" type="text" value="1" min="0" max="10">
                        <span class="product_count_item number-increment"> <i class="ti-plus"></i></span>
                    </div>
                    <p>$5</p>
                </div>
              <div class="add_to_cart">
                  <a asp-action="AddToCart" asp-controller="LlOrders" asp-route-id="@item.ProductId" class="btn_3">add to cart</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>}